# data paths and filenames
location = 'ACEENA'
input_path = '../raw_data/rrm/ena_rrm/'
input_filehead = 'ena_ne32x32pg2'
output_path = '../prep_data/'+location+'/model/'
output_filehead = 'E3SMv2_'+location

# time resolution in seconds
dt = 300

# variable names
lat = lat
lon = lon
