# data paths and filenames
model_input_path: '../raw_data/model/'  # '../raw_data/rrm/ena_rrm/'
model_input_filehead: 'E3SMv2_SGP_ENA_2011_2020'  # 'ena_ne32x32pg2'

obs_input_path: '../raw_data/obs/'

# variable names (in future, can expand this to contain each model variable name so that they aren't hard coded)
E3SMsubdomain: True
E3SMdomain_range: '330e_to_335e_37n_to_42n'

# # model longitude and latitude limits
# latmin: 37
# latmax: 42
# lonmin: 330
# lonmax: 335

# time frequency in seconds
model_aircraft_dt: 60      #interpolated
model_surface_dt: 3600     #instantaneous
model_profile_dt: 3600     #instantaneous
obs_aircraft_dt: 60        #median or average    
obs_surface_dt: 300        #median or average
obs_satellite_dt: 3600     #instantaneous
